"""split realtime and static stop ids

Revision ID: 20fae1e49eee
Revises: aa2ae662e75b
Create Date: 2026-08-17 00:02:27.009511

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20fae1e49eee"
down_revision: str | Sequence[str] | None = "aa2ae662e75b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Rows written before this migration stored the *realtime* stop id in stop_id, so the
    # column is renamed in place (rt_stop_id) and stop_id is re-derived from the schedule
    # via (scheduled_trip_id, stop_sequence). History is rewritten, not discarded.
    op.add_column(
        "arrival_predictions", sa.Column("rt_stop_id", sa.String(length=64), nullable=True)
    )
    op.execute("UPDATE arrival_predictions SET rt_stop_id = stop_id")
    op.alter_column("arrival_predictions", "rt_stop_id", nullable=False)
    op.alter_column(
        "arrival_predictions", "stop_id", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.execute(
        """
        UPDATE arrival_predictions AS p
        SET stop_id = st.stop_id
        FROM stop_times AS st
        WHERE st.agency_key = p.agency_key
          AND st.trip_id = p.scheduled_trip_id
          AND st.stop_sequence = p.stop_sequence
        """
    )
    op.execute("UPDATE arrival_predictions SET stop_id = NULL WHERE scheduled_trip_id IS NULL")
    op.drop_constraint(op.f("uq_arrival_prediction_reading"), "arrival_predictions", type_="unique")
    op.create_unique_constraint(
        "uq_arrival_prediction_reading",
        "arrival_predictions",
        ["agency_key", "rt_trip_id", "rt_stop_id", "stop_sequence", "observed_at"],
    )
    op.add_column(
        "vehicle_observations", sa.Column("rt_stop_id", sa.String(length=64), nullable=True)
    )
    op.execute("UPDATE vehicle_observations SET rt_stop_id = stop_id, stop_id = NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_observations", "rt_stop_id")
    op.drop_constraint("uq_arrival_prediction_reading", "arrival_predictions", type_="unique")
    op.create_unique_constraint(
        op.f("uq_arrival_prediction_reading"),
        "arrival_predictions",
        ["agency_key", "rt_trip_id", "stop_id", "stop_sequence", "observed_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "arrival_predictions", "stop_id", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.drop_column("arrival_predictions", "rt_stop_id")
    # ### end Alembic commands ###
