"""schedule spine and observation tables

Revision ID: aa2ae662e75b
Revises:
Create Date: 2026-08-16 23:57:55.274797

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa2ae662e75b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("gtfs_agency_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("agency_key"),
    )
    op.create_table(
        "arrival_predictions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ingest_run_id", sa.BigInteger(), nullable=True),
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("rt_trip_id", sa.String(length=64), nullable=False),
        sa.Column("rt_route_id", sa.String(length=64), nullable=True),
        sa.Column("vehicle_id", sa.String(length=64), nullable=True),
        sa.Column("scheduled_trip_id", sa.String(length=64), nullable=True),
        sa.Column("route_id", sa.String(length=64), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=True),
        sa.Column("trip_start_seconds", sa.Integer(), nullable=True),
        sa.Column("stop_id", sa.String(length=64), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predicted_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("predicted_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delay_seconds", sa.Integer(), nullable=True),
        sa.Column("schedule_relationship", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agency_key",
            "rt_trip_id",
            "stop_id",
            "stop_sequence",
            "observed_at",
            name="uq_arrival_prediction_reading",
        ),
    )
    op.create_index(
        "ix_arrival_pred_stop_time",
        "arrival_predictions",
        ["agency_key", "stop_id", "predicted_arrival"],
        unique=False,
    )
    op.create_index(
        "ix_arrival_pred_trip",
        "arrival_predictions",
        ["agency_key", "rt_trip_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arrival_predictions_ingest_run_id"),
        "arrival_predictions",
        ["ingest_run_id"],
        unique=False,
    )
    op.create_table(
        "favorite_stops",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("stop_id", sa.String(length=64), nullable=False),
        sa.Column("walk_minutes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label", "agency_key", "stop_id"),
    )
    op.create_index(op.f("ix_favorite_stops_label"), "favorite_stops", ["label"], unique=False)
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("feed_kind", sa.String(length=32), nullable=False),
        sa.Column("feed_url", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_latency_ms", sa.Integer(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("response_bytes", sa.Integer(), nullable=True),
        sa.Column("feed_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("feed_age_seconds", sa.Integer(), nullable=True),
        sa.Column("is_stale", sa.Boolean(), nullable=True),
        sa.Column("entity_count", sa.Integer(), nullable=True),
        sa.Column("usable_count", sa.Integer(), nullable=True),
        sa.Column("rejected_count", sa.Integer(), nullable=True),
        sa.Column("persisted_count", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingest_runs_agency_key"), "ingest_runs", ["agency_key"], unique=False)
    op.create_index(
        op.f("ix_ingest_runs_requested_at"), "ingest_runs", ["requested_at"], unique=False
    )
    op.create_table(
        "routes",
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("route_id", sa.String(length=64), nullable=False),
        sa.Column("short_name", sa.String(length=32), nullable=True),
        sa.Column("long_name", sa.Text(), nullable=True),
        sa.Column("route_type", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("agency_key", "route_id"),
    )
    op.create_index(op.f("ix_routes_short_name"), "routes", ["short_name"], unique=False)
    op.create_table(
        "service_exceptions",
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("service_id", sa.String(length=64), nullable=False),
        sa.Column("exception_date", sa.Date(), nullable=False),
        sa.Column("exception_type", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("agency_key", "service_id", "exception_date"),
    )
    op.create_table(
        "services",
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("service_id", sa.String(length=64), nullable=False),
        sa.Column("monday", sa.Boolean(), nullable=False),
        sa.Column("tuesday", sa.Boolean(), nullable=False),
        sa.Column("wednesday", sa.Boolean(), nullable=False),
        sa.Column("thursday", sa.Boolean(), nullable=False),
        sa.Column("friday", sa.Boolean(), nullable=False),
        sa.Column("saturday", sa.Boolean(), nullable=False),
        sa.Column("sunday", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("agency_key", "service_id"),
    )
    op.create_table(
        "stop_times",
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("trip_id", sa.String(length=64), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=False),
        sa.Column("stop_id", sa.String(length=64), nullable=False),
        sa.Column("arrival_seconds", sa.Integer(), nullable=True),
        sa.Column("departure_seconds", sa.Integer(), nullable=True),
        sa.Column("timepoint", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("agency_key", "trip_id", "stop_sequence"),
    )
    op.create_index(
        "ix_stop_times_stop",
        "stop_times",
        ["agency_key", "stop_id", "arrival_seconds"],
        unique=False,
    )
    op.create_table(
        "stops",
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("stop_id", sa.String(length=64), nullable=False),
        sa.Column("stop_code", sa.String(length=32), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("agency_key", "stop_id"),
    )
    op.create_table(
        "vehicle_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ingest_run_id", sa.BigInteger(), nullable=True),
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("vehicle_id", sa.String(length=64), nullable=False),
        sa.Column("rt_trip_id", sa.String(length=64), nullable=True),
        sa.Column("rt_route_id", sa.String(length=64), nullable=True),
        sa.Column("scheduled_trip_id", sa.String(length=64), nullable=True),
        sa.Column("route_id", sa.String(length=64), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("bearing", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("stop_id", sa.String(length=64), nullable=True),
        sa.Column("stop_sequence", sa.Integer(), nullable=True),
        sa.Column("current_status", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agency_key",
            "vehicle_id",
            "observed_at",
            "source",
            name="uq_vehicle_observation_reading",
        ),
    )
    op.create_index(
        "ix_vehicle_obs_route_time",
        "vehicle_observations",
        ["agency_key", "route_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_vehicle_obs_vehicle_time",
        "vehicle_observations",
        ["agency_key", "vehicle_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vehicle_observations_ingest_run_id"),
        "vehicle_observations",
        ["ingest_run_id"],
        unique=False,
    )
    op.create_table(
        "trips",
        sa.Column("agency_key", sa.String(length=32), nullable=False),
        sa.Column("trip_id", sa.String(length=64), nullable=False),
        sa.Column("route_id", sa.String(length=64), nullable=False),
        sa.Column("service_id", sa.String(length=64), nullable=False),
        sa.Column("direction_id", sa.Integer(), nullable=True),
        sa.Column("headsign", sa.Text(), nullable=True),
        sa.Column("shape_id", sa.String(length=64), nullable=True),
        sa.Column("start_seconds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agency_key", "route_id"],
            ["routes.agency_key", "routes.route_id"],
        ),
        sa.PrimaryKeyConstraint("agency_key", "trip_id"),
    )
    op.create_index(op.f("ix_trips_route_id"), "trips", ["route_id"], unique=False)
    op.create_index(
        "ix_trips_route_start", "trips", ["agency_key", "route_id", "start_seconds"], unique=False
    )
    op.create_index(op.f("ix_trips_service_id"), "trips", ["service_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trips_service_id"), table_name="trips")
    op.drop_index("ix_trips_route_start", table_name="trips")
    op.drop_index(op.f("ix_trips_route_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_vehicle_observations_ingest_run_id"), table_name="vehicle_observations")
    op.drop_index("ix_vehicle_obs_vehicle_time", table_name="vehicle_observations")
    op.drop_index("ix_vehicle_obs_route_time", table_name="vehicle_observations")
    op.drop_table("vehicle_observations")
    op.drop_table("stops")
    op.drop_index("ix_stop_times_stop", table_name="stop_times")
    op.drop_table("stop_times")
    op.drop_table("services")
    op.drop_table("service_exceptions")
    op.drop_index(op.f("ix_routes_short_name"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_ingest_runs_requested_at"), table_name="ingest_runs")
    op.drop_index(op.f("ix_ingest_runs_agency_key"), table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index(op.f("ix_favorite_stops_label"), table_name="favorite_stops")
    op.drop_table("favorite_stops")
    op.drop_index(op.f("ix_arrival_predictions_ingest_run_id"), table_name="arrival_predictions")
    op.drop_index("ix_arrival_pred_trip", table_name="arrival_predictions")
    op.drop_index("ix_arrival_pred_stop_time", table_name="arrival_predictions")
    op.drop_table("arrival_predictions")
    op.drop_table("agencies")
    # ### end Alembic commands ###
